//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libra.Graphics.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libra.Graphics.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AmbientOcclusionBlurPS {
            get {
                object obj = ResourceManager.GetObject("AmbientOcclusionBlurPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AmbientOcclusionMapPS {
            get {
                object obj = ResourceManager.GetObject("AmbientOcclusionMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BilateralFilterPS {
            get {
                object obj = ResourceManager.GetObject("BilateralFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomCombinePS {
            get {
                object obj = ResourceManager.GetObject("BloomCombinePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomExtractPS {
            get {
                object obj = ResourceManager.GetObject("BloomExtractPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CombinePS {
            get {
                object obj = ResourceManager.GetObject("CombinePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DepthMapPS {
            get {
                object obj = ResourceManager.GetObject("DepthMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DepthMapVS {
            get {
                object obj = ResourceManager.GetObject("DepthMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DirectTextureDrawPS {
            get {
                object obj = ResourceManager.GetObject("DirectTextureDrawPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DofCombinePS {
            get {
                object obj = ResourceManager.GetObject("DofCombinePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DownFilterPS {
            get {
                object obj = ResourceManager.GetObject("DownFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EdgePS {
            get {
                object obj = ResourceManager.GetObject("EdgePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FullScreenQuadVS {
            get {
                object obj = ResourceManager.GetObject("FullScreenQuadVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GaussianFilterPS {
            get {
                object obj = ResourceManager.GetObject("GaussianFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LightScatteringPS {
            get {
                object obj = ResourceManager.GetObject("LightScatteringPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearDepthMapPS {
            get {
                object obj = ResourceManager.GetObject("LinearDepthMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearDepthMapVS {
            get {
                object obj = ResourceManager.GetObject("LinearDepthMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MonochromePS {
            get {
                object obj = ResourceManager.GetObject("MonochromePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NegativeFilterPS {
            get {
                object obj = ResourceManager.GetObject("NegativeFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalEdgeDetectPS {
            get {
                object obj = ResourceManager.GetObject("NormalEdgeDetectPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalMapPS {
            get {
                object obj = ResourceManager.GetObject("NormalMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalMapVS {
            get {
                object obj = ResourceManager.GetObject("NormalMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadialFilterPS {
            get {
                object obj = ResourceManager.GetObject("RadialFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ScanlinePS {
            get {
                object obj = ResourceManager.GetObject("ScanlinePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMapBasicPS {
            get {
                object obj = ResourceManager.GetObject("ShadowMapBasicPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMapVariancePS {
            get {
                object obj = ResourceManager.GetObject("ShadowMapVariancePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMapVS {
            get {
                object obj = ResourceManager.GetObject("ShadowMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SingleColorObjectPS {
            get {
                object obj = ResourceManager.GetObject("SingleColorObjectPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SingleColorObjectVS {
            get {
                object obj = ResourceManager.GetObject("SingleColorObjectVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UpFilterPS {
            get {
                object obj = ResourceManager.GetObject("UpFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
