//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libra.Graphics.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libra.Graphics.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] BilateralFilterPS {
            get {
                object obj = ResourceManager.GetObject("BilateralFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomCombineFilterPS {
            get {
                object obj = ResourceManager.GetObject("BloomCombineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomExtractFilterPS {
            get {
                object obj = ResourceManager.GetObject("BloomExtractFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CloudLayerFilterPS {
            get {
                object obj = ResourceManager.GetObject("CloudLayerFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CloudPS {
            get {
                object obj = ResourceManager.GetObject("CloudPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CloudVS {
            get {
                object obj = ResourceManager.GetObject("CloudVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CombineFilterPS {
            get {
                object obj = ResourceManager.GetObject("CombineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DepthMapPS {
            get {
                object obj = ResourceManager.GetObject("DepthMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DepthMapVS {
            get {
                object obj = ResourceManager.GetObject("DepthMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DepthVarianceMapPS {
            get {
                object obj = ResourceManager.GetObject("DepthVarianceMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DofCombineFilterPS {
            get {
                object obj = ResourceManager.GetObject("DofCombineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DownFilterPS {
            get {
                object obj = ResourceManager.GetObject("DownFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EdgeFilterPS {
            get {
                object obj = ResourceManager.GetObject("EdgeFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExponentialFogFilterPS {
            get {
                object obj = ResourceManager.GetObject("ExponentialFogFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FluidPS {
            get {
                object obj = ResourceManager.GetObject("FluidPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FluidRippleFilterPS {
            get {
                object obj = ResourceManager.GetObject("FluidRippleFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FluidVS {
            get {
                object obj = ResourceManager.GetObject("FluidVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FullScreenQuadViewRayVS {
            get {
                object obj = ResourceManager.GetObject("FullScreenQuadViewRayVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FullScreenQuadVS {
            get {
                object obj = ResourceManager.GetObject("FullScreenQuadVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GaussianFilterPS {
            get {
                object obj = ResourceManager.GetObject("GaussianFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeightFogFilterPS {
            get {
                object obj = ResourceManager.GetObject("HeightFogFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeightToGradientFilterPS {
            get {
                object obj = ResourceManager.GetObject("HeightToGradientFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeightToNormalFilterPS {
            get {
                object obj = ResourceManager.GetObject("HeightToNormalFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LightScatteringFilterPS {
            get {
                object obj = ResourceManager.GetObject("LightScatteringFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearDepthMapColorFilterPS {
            get {
                object obj = ResourceManager.GetObject("LinearDepthMapColorFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearDepthMapPS {
            get {
                object obj = ResourceManager.GetObject("LinearDepthMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearDepthMapVS {
            get {
                object obj = ResourceManager.GetObject("LinearDepthMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearFogDepthMapPS {
            get {
                object obj = ResourceManager.GetObject("LinearFogDepthMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearFogDepthMapVS {
            get {
                object obj = ResourceManager.GetObject("LinearFogDepthMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinearFogFilterPS {
            get {
                object obj = ResourceManager.GetObject("LinearFogFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MonochromeFilterPS {
            get {
                object obj = ResourceManager.GetObject("MonochromeFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NegativeFilterPS {
            get {
                object obj = ResourceManager.GetObject("NegativeFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalEdgeDetectFilterPS {
            get {
                object obj = ResourceManager.GetObject("NormalEdgeDetectFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalMapPS {
            get {
                object obj = ResourceManager.GetObject("NormalMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NormalMapVS {
            get {
                object obj = ResourceManager.GetObject("NormalMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ParticlePS {
            get {
                object obj = ResourceManager.GetObject("ParticlePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ParticleVS {
            get {
                object obj = ResourceManager.GetObject("ParticleVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadialFilterPS {
            get {
                object obj = ResourceManager.GetObject("RadialFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ScanlineFilterPS {
            get {
                object obj = ResourceManager.GetObject("ScanlineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowOcclusionMapBasicPS {
            get {
                object obj = ResourceManager.GetObject("ShadowOcclusionMapBasicPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SingleColorObjectPS {
            get {
                object obj = ResourceManager.GetObject("SingleColorObjectPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SingleColorObjectVS {
            get {
                object obj = ResourceManager.GetObject("SingleColorObjectVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOBlurFilterPS {
            get {
                object obj = ResourceManager.GetObject("SSAOBlurFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOCombineFilterPS {
            get {
                object obj = ResourceManager.GetObject("SSAOCombineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOMapColorFilterPS {
            get {
                object obj = ResourceManager.GetObject("SSAOMapColorFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOMapPS {
            get {
                object obj = ResourceManager.GetObject("SSAOMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UpFilterPS {
            get {
                object obj = ResourceManager.GetObject("UpFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VolumetricFogCombineFilterPS {
            get {
                object obj = ResourceManager.GetObject("VolumetricFogCombineFilterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VolumetricFogMapPS {
            get {
                object obj = ResourceManager.GetObject("VolumetricFogMapPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VolumetricFogMapVS {
            get {
                object obj = ResourceManager.GetObject("VolumetricFogMapVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
