//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libra.Graphics.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libra.Graphics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AlphaTestEffectPSAlphaTestEqNe {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectPSAlphaTestEqNe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectPSAlphaTestEqNeNoFog {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectPSAlphaTestEqNeNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectPSAlphaTestLtGt {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectPSAlphaTestLtGt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectPSAlphaTestLtGtNoFog {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectPSAlphaTestLtGtNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectVSAlphaTest {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectVSAlphaTest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectVSAlphaTestNoFog {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectVSAlphaTestNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectVSAlphaTestVc {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectVSAlphaTestVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AlphaTestEffectVSAlphaTestVcNoFog {
            get {
                object obj = ResourceManager.GetObject("AlphaTestEffectVSAlphaTestVcNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasic {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicPixelLighting {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicPixelLighting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicPixelLightingTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicPixelLightingTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicTxNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicTxNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicVertexLighting {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicVertexLighting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicVertexLightingNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicVertexLightingNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicVertexLightingTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicVertexLightingTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectPSBasicVertexLightingTxNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectPSBasicVertexLightingTxNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasic {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicOneLight {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicOneLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicOneLightTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicOneLightTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicOneLightTxVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicOneLightTxVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicOneLightVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicOneLightVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicPixelLighting {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicPixelLighting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicPixelLightingTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicPixelLightingTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicPixelLightingTxVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicPixelLightingTxVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicPixelLightingVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicPixelLightingVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicTxNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicTxNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicTxVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicTxVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicTxVcNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicTxVcNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVcNoFog {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVcNoFog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVertexLighting {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVertexLighting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVertexLightingTx {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVertexLightingTx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVertexLightingTxVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVertexLightingTxVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasicEffectVSBasicVertexLightingVc {
            get {
                object obj = ResourceManager.GetObject("BasicEffectVSBasicVertexLightingVc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpriteEffectPS {
            get {
                object obj = ResourceManager.GetObject("SpriteEffectPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpriteEffectVS {
            get {
                object obj = ResourceManager.GetObject("SpriteEffectVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
